# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/dominikbarlow/Desktop/ECS 36C Programming Assignments/Program4"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/dominikbarlow/Desktop/ECS 36C Programming Assignments/Program4/cmake-build-debug"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/dominikbarlow/Desktop/ECS 36C Programming Assignments/Program4/cmake-build-debug/CMakeFiles" "/Users/dominikbarlow/Desktop/ECS 36C Programming Assignments/Program4/cmake-build-debug/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/dominikbarlow/Desktop/ECS 36C Programming Assignments/Program4/cmake-build-debug/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Program4

# Build rule for target.
Program4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Program4
.PHONY : Program4

# fast build rule for target.
Program4/fast:
	$(MAKE) -f CMakeFiles/Program4.dir/build.make CMakeFiles/Program4.dir/build
.PHONY : Program4/fast

CheckerRunner.o: CheckerRunner.cpp.o

.PHONY : CheckerRunner.o

# target to build an object file
CheckerRunner.cpp.o:
	$(MAKE) -f CMakeFiles/Program4.dir/build.make CMakeFiles/Program4.dir/CheckerRunner.cpp.o
.PHONY : CheckerRunner.cpp.o

CheckerRunner.i: CheckerRunner.cpp.i

.PHONY : CheckerRunner.i

# target to preprocess a source file
CheckerRunner.cpp.i:
	$(MAKE) -f CMakeFiles/Program4.dir/build.make CMakeFiles/Program4.dir/CheckerRunner.cpp.i
.PHONY : CheckerRunner.cpp.i

CheckerRunner.s: CheckerRunner.cpp.s

.PHONY : CheckerRunner.s

# target to generate assembly for a file
CheckerRunner.cpp.s:
	$(MAKE) -f CMakeFiles/Program4.dir/build.make CMakeFiles/Program4.dir/CheckerRunner.cpp.s
.PHONY : CheckerRunner.cpp.s

Trie.o: Trie.cpp.o

.PHONY : Trie.o

# target to build an object file
Trie.cpp.o:
	$(MAKE) -f CMakeFiles/Program4.dir/build.make CMakeFiles/Program4.dir/Trie.cpp.o
.PHONY : Trie.cpp.o

Trie.i: Trie.cpp.i

.PHONY : Trie.i

# target to preprocess a source file
Trie.cpp.i:
	$(MAKE) -f CMakeFiles/Program4.dir/build.make CMakeFiles/Program4.dir/Trie.cpp.i
.PHONY : Trie.cpp.i

Trie.s: Trie.cpp.s

.PHONY : Trie.s

# target to generate assembly for a file
Trie.cpp.s:
	$(MAKE) -f CMakeFiles/Program4.dir/build.make CMakeFiles/Program4.dir/Trie.cpp.s
.PHONY : Trie.cpp.s

checker.o: checker.cpp.o

.PHONY : checker.o

# target to build an object file
checker.cpp.o:
	$(MAKE) -f CMakeFiles/Program4.dir/build.make CMakeFiles/Program4.dir/checker.cpp.o
.PHONY : checker.cpp.o

checker.i: checker.cpp.i

.PHONY : checker.i

# target to preprocess a source file
checker.cpp.i:
	$(MAKE) -f CMakeFiles/Program4.dir/build.make CMakeFiles/Program4.dir/checker.cpp.i
.PHONY : checker.cpp.i

checker.s: checker.cpp.s

.PHONY : checker.s

# target to generate assembly for a file
checker.cpp.s:
	$(MAKE) -f CMakeFiles/Program4.dir/build.make CMakeFiles/Program4.dir/checker.cpp.s
.PHONY : checker.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Program4"
	@echo "... CheckerRunner.o"
	@echo "... CheckerRunner.i"
	@echo "... CheckerRunner.s"
	@echo "... Trie.o"
	@echo "... Trie.i"
	@echo "... Trie.s"
	@echo "... checker.o"
	@echo "... checker.i"
	@echo "... checker.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

